cl2-job:
  runs-on: ubuntu-latest
  timeout-minutes: 5
  schedule:
    - cron: "0 */2 * * *"  # هر ۳ ساعت
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - run: |
        rm -f vip2.txt normal2.txt
        timeout 180s python cl2.py || echo "❌ cl2.py failed or skipped"
    - run: |
        if [[ -s vip2.txt || -s normal2.txt ]]; then
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vip2.txt normal2.txt
          git commit -m "auto update from cl2.py [skip ci]" || echo "No changes"
          git push || echo "skip push"
        else
          echo "⚠️ vip2.txt یا normal2.txt خالی یا موجود نیست، commit نشد"
        fi
